.travis.yml
src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
src/main/java/au/org/ala/biocache/writer/CSVRecordWriter.java
src/main/java/au/org/ala/biocache/writer/RecordWriterError.java
src/main/java/au/org/ala/biocache/writer/RecordWriterException.java
src/main/java/au/org/ala/biocache/writer/ShapeFileRecordWriter.java
src/main/java/au/org/ala/biocache/writer/TSVRecordWriter.java

Log files have indicated that resources have not been released consistently. This makes the cleanup more rigorous to avoid these issues in future.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>

issue #173 : Cleanup more rigourously in writer classes

---

src/main/webapp/WEB-INF/mainDispatcher-servlet.xml

Use of external resources packaged by:
https://github.com/living-atlases/ala-i18n
Other [similar PRs](https://github.com/search?q=is%3Apr+author%3Avjrj+org%3AAtlasOfLivingAustralia+ala-i18n+external&type=Issues).

Usage of external ala-i18n resources

---

.travis.yml
src/main/java/au/org/ala/biocache/dto/DownloadDoiDTO.java
src/main/java/au/org/ala/biocache/dto/DownloadRequestParams.java
src/main/java/au/org/ala/biocache/service/DoiService.java
src/main/java/au/org/ala/biocache/service/DownloadService.java
src/main/webapp/WEB-INF/messages.properties
src/test/java/au/org/ala/biocache/dao/PersistentQueueDAOTest.java
src/test/java/au/org/ala/biocache/dto/DownloadRequestParamsTest.java

Reverts AtlasOfLivingAustralia/biocache-service#411

Revert "issue #405 : CSDM custom templates"

---

.travis.yml
README.md
pom.xml

Sync with master

---

src/main/java/au/org/ala/biocache/service/LoggerRestService.java

discard logger response & catch and re-log any logging exception

issue #465

---

src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java

Tested search terms in the form of
- "xxxx"
- "xxxx"yy
- 'xxxx'
- 'xxxx'yyy
result:

Fixed issue #453

---

src/main/java/au/org/ala/biocache/web/OccurrenceController.java
src/test/java/au/org/ala/biocache/controller/OccurrenceControllerTest.java

fix for logging of user-agent on view occurrence record

issue #465 User-Agent passed on logging of Occurrence Record 

---

src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java

Fixed #448

---

src/main/java/au/org/ala/biocache/web/AbstractSecureController.java
src/main/java/au/org/ala/biocache/web/OccurrenceController.java
src/main/webapp/WEB-INF/ehcache.xml
src/test/java/au/org/ala/biocache/controller/OccurrenceControllerTest.java

added email address validation, check email parameter meets RFC 822.
Also fixed rate limit window (300 seconds) to match 5 minute.

Feature/issue #343 added email validation

---

src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java

fixed biocache-service #490

---

src/main/java/au/org/ala/biocache/service/DownloadService.java

Set correct permissions (read) to download file and parent folders

Set correct permissions

---

src/main/webapp/WEB-INF/jsp/homePage.jsp
src/main/webapp/WEB-INF/jsp/oldapi.jsp

issue #504 updates to oldapi page

---

src/main/java/au/org/ala/biocache/web/OccurrenceController.java

This is the rebased version of #515

Hotfix issue #513 disable occurance log event rebased

---

scripts/migrateUserAssertions/qa_format.py

Removed use of csv reader. Use normal file reading instead.

fixed user_assertions migration script

---

src/main/java/au/org/ala/biocache/service/NameMatchSpeciesLookupService.java

Aligns SpeciesLookupService inconsistencies when service.bie.enabled=false

fix for occurrences/facet/download

---

pom.xml
src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java
src/main/java/au/org/ala/biocache/web/WMSController.java

https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/331
https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/332
developed by @adam-collins and reviewed by @djtfmartin

Fixes for WMS issues

---

solr/conf/managed-schema
src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
src/main/java/au/org/ala/biocache/service/AssertionService.java

added 'userVerified' field

---

src/main/java/au/org/ala/biocache/web/OccurrenceController.java

See https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/403
This change exposes ad-hoc properties supplied in non darwin core in the `miscProperties` field so they will be visible on record pages.
As an example, take from data in dr10487 - see https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/196

Work for la-pipelines/issues/403

---

src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
src/main/java/au/org/ala/biocache/stream/ProcessDownload.java
src/main/java/au/org/ala/biocache/web/WMSController.java

Includes fix for spatial-service and webportal/occurrences.gz

421 json.facet for bbox request

---

src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java

Fix flimit setting when paging through

437 flimit

---

src/main/java/au/org/ala/biocache/web/OccurrenceController.java

for issue https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/484
front-end needs to know if a record is sensitive.

return if a record is sensitive

---

src/main/java/au/org/ala/biocache/dto/AssertionCodes.java
src/main/java/au/org/ala/biocache/web/AssertionController.java

for https://github.com/AtlasOfLivingAustralia/alerts/issues/134
added a new type of user assertion: **Biosecurity issue**

added a new type of user assertion: Biosecurity issue.

---

src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java

for issue #724 
with the change you have
<br/><br/>
in [occurrences/search?q=*&sort=first_loaded_date&dir=desc&pageSize=20&facets=basis_of_record&fq=id:95cb6dcc-abb3-4690-a8b5-209b600066a9](url)

added a hasUserAssertions field

---

pom.xml
src/main/java/au/org/ala/biocache/dto/FacetThemes.java
src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java
src/main/java/au/org/ala/biocache/web/OccurrenceController.java
src/main/java/au/org/ala/biocache/web/WMSController.java
src/test/java/au/org/ala/biocache/util/SolrUtils.java

Fix for typeStatus multi valued field.
Warning - this change is tied to https://github.com/gbif/pipelines/issues/688
Deploying this will need to be done in tandem with SOLR schema changes and pipelines changes.

fix for #739

---

src/main/java/au/org/ala/biocache/service/ListsService.java

Add paging to speciesListItems call

---

src/main/java/au/org/ala/biocache/dto/SearchRequestDTO.java
src/main/java/au/org/ala/biocache/web/MapController.java
src/main/java/au/org/ala/biocache/web/WMSController.java
src/main/java/au/org/ala/biocache/web/WMSOSGridController.java

- fix map image
- remove unused wms cache parameter
- make some wms/reflect and related parameters optional

Fix map image

---

src/main/java/au/org/ala/biocache/dao/QidCacheDAOImpl.java
src/main/java/au/org/ala/biocache/dto/SearchRequestDTO.java
src/main/java/au/org/ala/biocache/service/DataQualityService.java
src/main/java/au/org/ala/biocache/web/MapController.java
src/main/java/au/org/ala/biocache/web/WMSController.java
src/main/java/au/org/ala/biocache/web/WMSOSGridController.java

Add caching to significantly reduce requests to data-quality-service.

Data quality service caching

---

.travis.yml
build.gradle
settings.gradle
src/main/java/au/org/ala/biocache/service/AuthService.java
src/main/java/au/org/ala/biocache/service/DownloadService.java
src/main/webapp/WEB-INF/ehcache.xml
src/test/java/au/org/ala/biocache/controller/AssertionsControllerIT.java
src/test/java/au/org/ala/biocache/controller/DownloadControllerIT.java
src/test/java/au/org/ala/biocache/controller/ExploreControllerIT.java
src/test/java/au/org/ala/biocache/controller/OccurrenceControllerIT.java
src/test/java/au/org/ala/biocache/controller/OccurrenceControllerMockedDAOTestIT.java
src/test/java/au/org/ala/biocache/controller/ScatterplotControllerIT.java
src/test/java/au/org/ala/biocache/controller/WMSControllerIT.java
src/test/java/au/org/ala/biocache/controller/WMSOSGridControllerIT.java
src/test/java/au/org/ala/biocache/dao/QueryFormatTest.java
src/test/java/au/org/ala/biocache/dao/SolrIndexDAOImplIT.java
src/test/java/au/org/ala/biocache/dto/DownloadRequestParamsIT.java
src/test/java/au/org/ala/biocache/service/AuthServiceTest.java
src/test/java/au/org/ala/biocache/service/DownloadServiceTest.java
src/test/java/au/org/ala/biocache/service/SpatialServiceIntegrationTest.java
src/test/java/au/org/ala/biocache/util/QidCacheIT.java
src/test/java/au/org/ala/biocache/util/solr/FieldMappedSolrClientSpecIT.groovy
src/test/resources/biocache-test-config.properties

The latest version of `ala-ws-spring-security` fixes the issue with the access to the `AlaUserProfile.userId` property also supports Cognito as OIDC auth provider. 
Change of AlaUserProfile to an interface and rename of name fields.

update of ala-ws-spring-security v4.4.0-SNAPSHOT

---

.travis.yml
build.gradle
src/main/java/au/org/ala/biocache/config/Application.java
src/main/java/au/org/ala/biocache/config/SecurityConfig.java
src/main/java/au/org/ala/biocache/service/AuthService.java
src/main/java/au/org/ala/biocache/service/DoiService.java
src/main/java/au/org/ala/ws/config/AlaWsConfig.java
src/main/java/au/org/ala/ws/tokens/TokenClient.java
src/main/java/au/org/ala/ws/tokens/TokenInterceptor.java
src/main/java/au/org/ala/ws/tokens/TokenService.java
src/test/java/au/org/ala/biocache/service/AuthServiceTest.java
src/test/resources/biocache-test-config.properties

resolution of #789
ported ala-ws-plugin token interceptor for retrofit and configuration of DOI service

Use JWT to authenticate against DOI service

---

src/main/java/au/org/ala/biocache/service/ListsService.java
src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
src/main/java/au/org/ala/biocache/web/OccurrenceController.java
src/test/java/au/org/ala/biocache/util/QueryFormatUtilsSpec.groovy
src/test/resources/au/org/ala/biocache/util/dr123_items.json
src/test/resources/au/org/ala/biocache/util/dr456_items.json

expand facets/download lists columns

---

src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java

merge to develop after 3.4.0 is released.

#887 fix offline download sort

---

src/main/java/au/org/ala/biocache/dao/SearchDAO.java
src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
src/main/java/au/org/ala/biocache/util/WmsEnv.java
src/main/java/au/org/ala/biocache/web/WMSController.java

hexbin wms

---

build.gradle
src/main/java/au/org/ala/biocache/service/LoggerRestService.java
src/test/java/au/org/ala/biocache/dao/SolrIndexDAOImplIT.java
src/test/java/au/org/ala/biocache/service/LoggerServiceSpec.groovy
src/test/java/au/org/ala/biocache/util/QueryFormatUtilsSpec.groovy
src/test/java/au/org/ala/biocache/util/solr/FieldMappedSolrClientSpecIT.groovy

#937 spock based unit tests fix

---

src/main/java/au/org/ala/biocache/service/DownloadService.java

#943 add option to disable download logging

---

src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java

#917 support unmapped fields in occurrences/search

---

build.gradle
src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
src/main/java/au/org/ala/biocache/service/AlaLayersService.java
src/main/java/au/org/ala/biocache/service/LayersService.java

#960 update indexed fields

---

build.gradle
src/main/java/au/org/ala/biocache/dao/JsonPersistentQueueDAOImpl.java
src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
src/main/java/au/org/ala/biocache/service/AlaLayersService.java
src/main/java/au/org/ala/biocache/service/LayersService.java
src/main/java/au/org/ala/biocache/util/AlaUserProfileDeserializer.java
src/test/java/au/org/ala/biocache/controller/OccurrenceControllerIT.java

901 fix restarting downloads
