- src/main/java/au/org/ala/biocache/web/WMSController.java
across, otherwise additional escapes are added in.
> Queries recovered from qids require the fomatted query to be copied 

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
Http species ids were not being correctly turned into a left-right range
> Handle http: lsids for taxa searches properly

- .gitignore
- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/service/AlaImageMetadataService.java
- src/main/java/au/org/ala/biocache/service/DownloadService.java
- src/main/java/au/org/ala/biocache/util/AlaFileUtils.java
- src/main/java/au/org/ala/biocache/web/AssertionController.java
- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
- src/main/java/au/org/ala/biocache/web/UploadController.java
- src/main/java/au/org/ala/biocache/writer/ShapeFileRecordWriter.java
There were a number of cases where IO objects were not being reliably closed. In some cases they were being closed correctly, but were not using the Java-7 try-with-resources pattern for maintainability.
I didn't migrate the HttpClient-3 code to HttpClient-4 code, as this was just meant to be a short audit.
> Fix #119 Audit closure of IO objects

- src/main/java/au/org/ala/biocache/web/WMSController.java
Fixes issue #126 by adding null checks on the Integer objects returned from getCachedCount. The NullPointerExceptions resulting from the lack of null checks turned up in the biocache-b3 logs yesterday.
> issue #126 : Add null check on returns from getCachedCount

- src/main/java/au/org/ala/biocache/web/WMSController.java
Avoids corrupting the parsed BBOX when exceptions occur, and checks for cases where the bbox didn't have enough positions available.
Fixes #143
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
> issue #143 : Parse BBOX more consistently

- src/main/java/au/org/ala/biocache/util/OccurrenceUtils.java
Adds a null check to OccurrenceUtils.getAllVersionsByUuid to respond to a NullPointerException found in the biocache-b4 logs.
Fixes #141
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
> issue #141 : Add null check in OccurrenceUtils.getAllVersionsByUuid

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
Check was being done on the first character and then a substring was being called without a length check.
This fixes #142 by adding a length check before calling substring, and using a constant otherwise.
Signed-off-by: Peter Ansell <p_ansell@yahoo.com>
> issue #142 : Fix StringIndexOutOfBoundsException in runSolrQuery

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/service/DownloadService.java
- src/main/java/au/org/ala/biocache/writer/CSVRecordWriter.java
- src/main/java/au/org/ala/biocache/writer/RecordWriterError.java
- src/main/java/au/org/ala/biocache/writer/ShapeFileRecordWriter.java
- src/main/java/au/org/ala/biocache/writer/TSVRecordWriter.java
Explicitly ``initialise`` ``RecordWriter`` implementations after their constructor completes so we always have a ``RecordWriter`` object reference available to call ``finalise`` on. In the case of #202, this will ensure that we have the best chance of explicitly calling back into GeoTools to close the ``Transaction`` we open when we create/initialise a ``ShapeFileRecordWriter``.
This also fixes cases where ``finalise`` was not called consistently from within a dedicated ``finally`` block, which could also have triggered the same behaviour.
This also adds ``java.io.Closeable`` to ``RecordWriterError`` so that standard static bug checkers in future can be used to identify when we are not consistently closing objects, but does not yet switch from ``finalise`` to ``close`` or …
> Fix #202 : Explicitly initialise RecordWriter implementations after their constructor completes

- src/main/java/au/org/ala/biocache/web/WMSController.java
fixes for #351 to give a default SRS for getFeatureInfo.
Created a PR here as I dont think using the default of 900913 for an SRS makes any sense (its not longer recognised by geotools libraries).
> fixes for #351

- src/main/java/au/org/ala/biocache/web/WMSController.java
Naive attempt at fixing #377 based on inspection of the URL that was failing due to a missing ampersand.
> issue #377 : Add ampersand between OGC and query parameters

- crowdin.yml
Following the conversation in https://github.com/AtlasOfLivingAustralia/downloads-plugin/issues/40 I created this crowdin-cli configuration to keep in sync this ALA repository with crowdin easily.
For now I only used to updated crowdin with some minor updates in the github file:
```
$ crowdin upload sources                                                                
File 'biocache-service/messages.properties' - OK
```
Anyone knows why translations are not committed to this repository and loaded from `/data`? I'm just curious.
> crowdin-cli sync configuration

- src/main/java/au/org/ala/biocache/web/WMSController.java
Simple fix for #417. 
Tested in production:
> Fix for #417

- src/main/java/au/org/ala/biocache/web/ScatterplotController.java
Internal-only private variable, so simple to switch it from `private static final` to `private`
Allows control to be moved to configuration rather than code when attempting to minimise the impact of Scatterplots on general availability.
> issue #423 Make Scatterplot page size configurable

- pom.xml
- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/test/java/au/org/ala/biocache/dao/FilterQueryParserTest.java
For fq=-(month:"02") or fq=-(month:"02" OR month:"03") '02' is not translated to 'Februray'
Below is current query result.
```
"activeFacetMap": {
"-(month": {
"name": "-(month",
"displayName": "-(month:\"02\")",
"value": "\"02\")"
}
}
"activeFacetMap": {
"-(month": {
"name": "-(month",
"displayName": "-(month:\"02\" OR Month:\"March\")",
"value": "\"02\" OR month:\"03\")"
}
}
```
With changes in this PR
```
"activeFacetMap": {
"-(month": {
"name": "-(month",
"displayName": "-(Month:\"February\")",
"value": "\"02\")"
}
}
"activeFacetMap": {
"-(month": {
"name": "-(month",
"displayName": "-(Month:\"February\" OR Month:\"March\")",
"value": "\"02\" OR month:\"03\")"
}
}
```
Ref #434
> format fq doesn't work for fqs start with "-("

- src/main/webapp/META-INF/context.xml
- src/main/webapp/WEB-INF/web.xml
updated context.xml to support deployment to tomcat 8.5 / 9
I've confirmed deployment of war on:
- tomcat 8.5.54
- tomcat 9.0.34 
@djtfmartin could you please confirm if there is and ramifications of removing antiJarLocking? It does not seem to be required but I don't understand the reason it was enabled originally.
> Tomcat 8.5+9 update

- src/main/java/au/org/ala/biocache/service/DownloadService.java
I've added a new `doi.txt` to the download zip file containing the DOI reference. The file is only added if `mintDoi=true` as per AtlasOfLivingAustralia/ALA4R#60
Note: This issue has been difficult to test in dev due to dependencies with external services.
> issue #456 Add doi.txt file to download ZIP

- pom.xml
- src/main/java/au/org/ala/biocache/web/BuildInfoController.java
- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
- src/main/resources/buildInfo.properties
- src/main/resources/runtimeEnvironment.properties
- src/main/webapp/WEB-INF/decorators/main.jsp
- src/main/webapp/WEB-INF/jsp/buildInfo.jsp
I have written a new `BuildInfoController` and view that mimics [ala-admin-plugin/BuildInfoController.groovy](https://github.com/AtlasOfLivingAustralia/ala-admin-plugin/blob/master/grails-app/controllers/au/org/ala/admin/BuildInfoController.groovy).
Build and runtime properties are injected via maven `git-commit-id-plugin` plugin.
The build info can be access at `/ws/buildInfo` for html view or `/ws/buildInfo.json` for JSON output.
> feature #376 expose app.version

- src/main/java/au/org/ala/biocache/web/DownloadController.java
When a user re-execute the same download (same email/params) which still pending, we will return the initial statusUrl 
Before, we returned the new statusUrl (with the new downloadID) which redirected to a failed status.
Now, we returned to the initial statusUrl so the download confirm popup is successful.
> #55 Download status updates

- pom.xml
incorporate fix the updates to the ala-parent-pom v13 which will reinstate the automated junit4 tests.
> bumped parent pom to v13

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/dto/IndexFieldDTO.java
- src/main/webapp/WEB-INF/messages.properties
There's a request in https://github.com/AtlasOfLivingAustralia/DataQuality/issues/116 to add a new field for wiki link of some fields.
With this change, the `index/fields` will return below for those with a valid wiki link
And changes will also be made to download plugin (a new column further information added) so `fields` page will look like this:
> added a new filed into indexFieldDTO

- src/main/java/au/org/ala/biocache/dto/DownloadDoiDTO.java
- src/main/java/au/org/ala/biocache/dto/DownloadRequestParams.java
- src/main/java/au/org/ala/biocache/service/DoiService.java
- src/main/java/au/org/ala/biocache/service/DownloadService.java
- src/main/webapp/WEB-INF/messages.properties
- src/test/java/au/org/ala/biocache/dao/PersistentQueueDAOTest.java
- src/test/java/au/org/ala/biocache/dto/DownloadRequestParamsTest.java
This PR is intended to resolve the issues with merge and subsequent revert of PR #411 & #445 and from branches from [`hotfix/doimetadata`](https://github.com/AtlasOfLivingAustralia/biocache-service/tree/hotfix/doimetadata) (closed PR #444).
The suggested code review changes from [PR #444](https://github.com/AtlasOfLivingAustralia/biocache-service/pull/444/files) have been made with the exception of https://github.com/AtlasOfLivingAustralia/biocache-service/pull/444/files#r405216593.
It should be possible to display templates configurable but I suggest a new PR to implement this.
> #405 client defined download email template

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/test/java/au/org/ala/biocache/dao/FilterQueryParserTest.java
- src/test/java/au/org/ala/biocache/dao/QueryFormatTest.java
Clips the quoted `extractedValue` at the next match of the termPattern. 
This should stop escaping of quotes when the next term is encounter. 
**Note:** if the quoted terms `extractedValue` contains a string that matches the termPattern then processing will terminate.
> Issue #502 occurrence search failed on fq=month:"03" month:"04"

- src/main/java/au/org/ala/biocache/web/DownloadController.java
- src/test/java/au/org/ala/biocache/controller/DownloadControllerTest.java
added validation of the userdetails for email address supplied with the download request. 
The user details properties must be:
- activated 
- !locked
- roles contains config `${download.auth.role:ROLE_USER}`
> issue #479 validate email address for offline downloads against user details

- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/test/java/au/org/ala/biocache/dao/FilterQueryParserTest.java
Old implementation failed to parse `license:"CC BY NC" license:"CC BY NC 4.0 (Int)" `
> updated implementation of QueryFormatUtils::parseFQ

- pom.xml
- src/main/java/au/org/ala/biocache/web/DownloadController.java
- src/test/java/au/org/ala/biocache/controller/DownloadControllerTest.java
This adds backwards compatibility for previous userdetails versions that do not expose the `activated` attribute for users.
Includes regression tests to ensure backwards compatibility in future.
> Hotfix for issue#540 : Backwards compatibility for userdetails

- src/main/java/au/org/ala/biocache/web/WMSController.java
set configurable default page size `wms.pagesize`
> issue #495 Fix hardcoded 1,000,000 page size for WMS uncertainty queries

- src/main/java/au/org/ala/biocache/web/DownloadController.java
- src/test/java/au/org/ala/biocache/controller/DownloadControllerTest.java
added config property `download.auth.bypass` to bypass authorisation of email for downloads
> issue #546 Download check for registered users should be optional via config

- src/main/java/au/org/ala/biocache/service/SpeciesLookupRestService.java
Added extra checks that the index into the lists (`unknownPos`) < all of the lists size.
The size of the unknown GUIDs (`unknown`) should be the same and the results of [Bulk lookup by GUID](https://api.ala.org.au/#ws110), any GUIDs that are not found will result in NULL within the results array.
> issue #390 : IndexOutOfBoundsException in SpeciesLookupRestService

- src/main/java/au/org/ala/biocache/service/ListsService.java
- src/test/java/au/org/ala/biocache/service/ListsServiceSpec.groovy
The `ListService:find` method performed a partial match if an exact match does not exists. This partial match is run in reverse order of the point at which the exact match should have appeared in the sorted list. 
If the find if for a `Kvp` that is > then and within the list then the index is set to the list size +1 which is causing a failure when trying a partial match.
> issue #524 : ListService::find fails with IndexOutOfBoundsException

- pom.xml
- src/main/java/au/org/ala/biocache/service/LoggerRestService.java
- src/test/java/au/org/ala/biocache/service/LoggerServiceSpec.groovy
Asynchronously processes the log events retrieving from a `BlockingQueue`. 
The implementation uses the ReactiveX (RxJava) library to setup a back pressure aware Flowable emitting LogEvents from the blocking queue when they become available. The subscription(Consumer) requests individual events to prevent standard buffering. 
The async logging configuration values: 
- `logger.service.queue.size` : the queue size before blocking occurs
- `logger.service.thread.pool` : ThreadPool asynchronously consuming log events
- `logger.service.throttle.delay` : throttle delay between sending events to the `logger-service`
> issue #514 send log events asynchronously

- pom.xml
- src/main/java/au/org/ala/biocache/service/AssertionService.java
- src/main/java/au/org/ala/biocache/web/AssertionController.java
- src/test/java/au/org/ala/biocache/service/AssertionServiceTest.java
1. Changed Biocache-service to add related record id, and related reason for `duplicate record `issue.
2. Changed to use Biocache-store-2.6.1 so that above mentioned fields can be saved.
3. `AssertionService` is created to wrap the add assertion action
> duplicate record assertions

- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
See issue https://github.com/AtlasOfLivingAustralia/biocache-service/issues/571
with this change:
1. when `searchParams.getFormattedQuery()` is empty, it gets expanded for the first time
2. once it's expanded, `searchParams.getFormattedQuery()` not empty so it will only be expanded when` forceQueryFormat == true`
3. when `forceQueryFormat`, formatFq will be set to null so dq profile only expanded once.
> expand dq profile only when it's not yet formatted

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/dto/DuplicateRecordDetails.java
- src/main/java/au/org/ala/biocache/dto/FacetThemes.java
- src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java
- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/main/java/au/org/ala/biocache/web/DuplicationController.java
- src/main/java/au/org/ala/biocache/web/ExploreController.java
- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
- src/main/java/au/org/ala/biocache/web/WMSController.java
- src/test/java/au/org/ala/biocache/dao/FilterQueryParserTest.java
- src/test/java/au/org/ala/biocache/dao/QueryFormatTest.java
Fixes for duplicate services to support the display of duplicate records on occurrence record pages.
Namely the service: `/ws/duplicates/<UUID>`
Also includes:
* Changes for taxonRankID for consistency with taxonRank
* Fix for heatmaps so that QID queries render
* Set content type on PNGs in WMS controller
> 239 duplicate services

- scripts/migrateUserAssertions/qa_format.py
The migration issue is caused by several factors:
-  `cqlsh COPY TO` command generates some values with surrounding ""
As a solution, I chose to manually remove them if a value starts and ends with "
- But another issue is `csv.DictReader` can't even read properly (see my screen capture in AtlasOfLivingAustralia/la-pipelines#291)
- The `csv.DictWriter `also has an issue I don't remember exactly. Look at the code
```
map = {}
map['key'] = k;
map['data'] = json.dumps(data[k], indent=False).replace('\n', '')
writer.writerow(map)
```
`map['data']` is the returned value of `json.dumps()`, there's no way it's not a valid json. But the reality is, migrated data field could be invalid. So I changed to write csv file manually.
As a result, I just changed to manually read csv file line by line and …
> fixed issues in migration script for #291

- src/main/java/au/org/ala/biocache/dao/IndexDAO.java
- src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
- src/main/java/au/org/ala/biocache/service/AssertionService.java
- src/test/java/au/org/ala/biocache/service/AssertionServiceTest.java
- This commit includes changes to update solr document after user assertion is addede/removed/verified.
- These 2 fields will be added to solr document:
> 1. `user_assertions` this is the assertion status of this record (string type)
>2. `assertion_user_id` this is the list of user ids who have made an annotation on this record (list<string> type)
- with these 2 fields added, user will be able to query solr with `fq=assertion_user_id:56528` and `fq=user_assertions:50001`
see below example
___
Changes were made per code review. Now the updated solr doc looks like this:
> update solr after user assertion is added/removed/verified

- solr/conf/managed-schema
- src/main/java/au/org/ala/biocache/dao/CassandraStoreDAOImpl.java
- src/main/java/au/org/ala/biocache/dao/IndexDAO.java
- src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
- src/main/java/au/org/ala/biocache/dao/StoreDAO.java
- src/main/java/au/org/ala/biocache/service/AssertionService.java
- src/main/java/au/org/ala/biocache/web/AssertionController.java
- src/test/java/au/org/ala/biocache/service/AssertionServiceTest.java
This PR provides an API to trigger indexing of all user assertions.
One possible scenario we need to handle is the record the assertion associated with no longer exists in solr.
For example, if we have assertions for records [id1, id2, id3, id4, id5] and suppose record with id3 no longer exists in solr.
By default, solr will create a new record with id3 and those user assertions fields which is not what we want.
So we specify _version_ = 1, meaning only update when the id exists. With this setting, solr throws an exception for id3, saying 'no match record found' which is what we expect. But the thing is, all other subsequent update calls fail. I've tried different ways, but none works. It should be a bug for solr. So 1 failed update causes all subsequent update to fail even when their ids …
> an API to trigger index of all user assertions

- src/main/java/au/org/ala/biocache/util/solr/FieldMappingUtil.java
- src/test/java/au/org/ala/biocache/util/solr/FieldMappingUtilSpec.groovy
AtlasOfLivingAustralia/la-pipelines#401 fix to the query term parser to handle extra operators `!` and `+`
> add assertion terms required to test property

- src/main/java/au/org/ala/biocache/service/AssertionService.java
As a reference, these 2 records are returned by the `fq=assertion_user_id:"10012"` search from prod
https://biocache.ala.org.au/occurrences/63c21147-d3b9-4454-9681-bbed1790d250
https://biocache.ala.org.au/occurrences/c6aaa0c9-6b06-4ef5-b0fa-dd3a402d5116
but user 10012 (Nimal Karunajeewa) only verified the user assertions.
Old code only checks the uids who created normal (non-verification) user assertions. The change is to get uids from all user assertions.
> assertionUserId also includes those user who made verification

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
- src/main/java/au/org/ala/biocache/dto/OccurrenceIndex.java
- src/main/java/au/org/ala/biocache/util/solr/FieldMappedSolrParams.java
- src/main/java/org/apache/solr/client/solrj/io/stream/AlaCloudSolrStream.java
Added an extended CloudSolrStream that allows for a single request to the SOLR cluster instead of numberOfShards*requests and returning numberOfShards duplicates.
> Custom CloudSolrStream

- scripts/migrateQids/qid_format.groovy
There are **118973** entries in prod `qid` database that have an empty `fq`
for example:
qid.rowkey = 1438652996011, line3 fqs = [, -(data_provider:* AND -data_provider:"Australian Seedbank Partnership" AND -data_provider:"Global Biodiversity Information Facility" AND -data_provider:"DigiVol" AND -data_provider:"Barcode of Life" AND -data_provider:"South Australia, Department of Environment, Water and Natural Resources" AND -data_provider:"Australia's Virtual Herbarium" AND -data_provider:"Citizen Science - ALA Website" AND -data_provider:"Australian National Insect Collection, CSIRO Entomology" AND -data_provider:"University of Adelaide" AND -data_provider:"BirdLife Australia" AND -data_provider:"Office of Environment and Heritage, Department of Premier and Cabinet representing the State …
> filter out empty fq which causes crash

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
AtlasOfLivingAustralia/la-pipelines#453 
- changed `qa` param value to check `includeall` (not camel case value)
- use `qa` param as the assertion name if not [ `all` | `incudeall` | `none` ]
> Epic/pipelines/453 qa=includeall not working

- src/main/java/au/org/ala/biocache/service/NameMatchSpeciesLookupService.java
Fixes the adding of conservation status and invasive status to checklist downloads.
> Fixes https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/477

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
This fix is for https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/468
1. Confirmed with Dave that `sensitive_raw_decimalLatitude, sensitive_raw_decimalLongitude, sensitive_raw_locality` not exist in Solr so the mapping to them has been removed.
2. Added other sensitive fields mapping.
> Updated the sensitive mapping list

- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
This is the fix for https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/430
1. `response.sendError(404, "Unrecognised ID")` has a default content type of `txt/html`, a function is created for a `applicaiton/json` type of response and this function can be used for any json handler calling `response.sendError`
2. Biocache-hubs will need change like this
> send 404 when no record found. response body set to JSON.

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
For issue https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/488
> check if queryParams.getMax() is valid before comparing it with count

- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
for issue https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/489 and https://github.com/AtlasOfLivingAustralia/la-pipelines/issues/490
1. handle `qa=`
2. do not use description as column name, instead, use qa label name
> don't use assertions.{id} as heading

- src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
replaced the use of regex pattern to parse string representation of luke response to use the QueryResponse access methods.
AtlasOfLivingAustralia/la-pipelines#481
> refactor index fields service

- pom.xml
- src/main/java/au/org/ala/biocache/web/CustomExceptionResolver.java
- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
- src/main/webapp/WEB-INF/mainDispatcher-servlet.xml
- src/test/java/au/org/ala/biocache/controller/OccurrenceControllerIT.java
- src/test/java/au/org/ala/biocache/controller/WMSOSGridControllerIT.java
- src/test/java/au/org/ala/biocache/controller/WMSOSGridControllerTest.java
- src/test/resources/springTest.xml
For https://github.com/AtlasOfLivingAustralia/biocache-service/issues/587
`org.springframework.web.servlet.PageNotFound` configured in mainDispatcher-servlet.xml is not an exception so I didn't handle it.
This change provides a custom exception resolver so we can sure the `model` can be converted to JSON when 'application/json' is specified (in this case ContentNegotiaingViewResolver tries to map the whole model into JSON)
I've written an interface to test error page, both /occurrence/test/1 and /test/2 show an error page
```
@RequestMapping(value = "occurrence/test/{id}", method = RequestMethod.GET)
public void test(@PathVariable String id) throws Exception {
if (id.equals("1")) {
throw new TransactionTimedOutException("alex transaction time out");
// throw new …
```
> a customized exception resolver to properly set model data

- src/main/java/au/org/ala/biocache/web/UploadController.java
The object being written into the file is
```
final class UploadStatus {
final String status;
final String description;
final Integer percentage;
```
so it failed to be converted to `Map<String, String>`
> corrected the function return type.

- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
The processed `raw_eventDate` value was not being returned with the occurrence JSON data. 
The issue was related to a check `value instanceof Date` when adding the eventDate value to the JSON, since the `raw_eventDate` field type is a string the date was not added. 
AtlasOfLivingAustralia/la-pipelines#504
> processed eventDate not returned with occurrence

- src/main/java/au/org/ala/biocache/dto/AssertionCodes.java
- src/main/java/au/org/ala/biocache/dto/QualityAssertion.java
- src/main/java/au/org/ala/biocache/service/AssertionService.java
for issue https://github.com/AtlasOfLivingAustralia/biocache-hubs/issues/504
there must be some assertions written into database with empty name, so I call `qa.setCode`  to populate name when `getAssertion` is called.
> fixed getByCode(int code) which returns null for user assertions code

- src/main/java/au/org/ala/biocache/dao/SearchDAO.java
- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/dto/HeatmapDTO.java
- src/main/java/au/org/ala/biocache/util/LegendItem.java
- src/main/java/au/org/ala/biocache/web/WMSController.java
- src/main/webapp/WEB-INF/ehcache.xml
This PR is the backport in branch 2.7.x of the heatmap fix done by ALA in 3.x
This backport has been tested (and is in production in France: https://openobs.mnhn.fr) on a 2.5.x branch.
This 2.7.x backport is similar to the 2.5.x but it was NOT tested because 2.7.x is not compatible with my current ALA deployment.
REMINDER: it has some requirements in term of SolR version and the schema should contains the "quad" field
Maybe we should create a separated 2.7.x branch?
```
<fieldType name="geohash"
class="solr.SpatialRecursivePrefixTreeFieldType"
datelineRule="ccwRect"
spatialContextFactory="org.locationtech.spatial4j.context.jts.JtsSpatialContextFactory"
validationRule="none"
distanceUnits="degrees"
autoIndex="true"
/>
<fieldType name="quad"
class="solr.SpatialRecursivePrefixTreeFieldType" …
```
> Backport Heatmap fix in 2.7.x

- src/main/java/au/org/ala/biocache/config/AppConfig.java
- src/main/java/au/org/ala/biocache/dto/SpatialSearchRequestParams.java
- src/main/java/au/org/ala/biocache/util/converter/FqConverter.java
- src/main/java/au/org/ala/biocache/util/converter/FqField.java
- src/main/java/au/org/ala/biocache/web/AutocompleteController.java
- src/main/java/au/org/ala/biocache/web/DeprecatedController.java
- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
- src/main/java/au/org/ala/biocache/web/WMSController.java
https://github.com/AtlasOfLivingAustralia/biocache-service/issues/778
This fixes the use case of a request with only one fq parameter and it just happens to contain a comma. e.g. `https://biocache.ala.org.au/occurrences/search?q=taxa%3A%22Geophila%22&qualityProfile=ALA&fq=collector%3A%22Forster%2C+P.I.%22`
> Remove fq delimiting by comma

- src/main/java/au/org/ala/biocache/dao/QidCacheDAOImpl.java
A fix for the error thrown when creating a qid using `bbox=true` and all occurrences in the query are missing longitude or latitude.
> fix for qid creation error

- src/main/java/au/org/ala/biocache/web/OccurrenceController.java
Adds `materialSampleID` to the occurrence record endpoint. Adding it here will also make it (automatically) appear on the occurrence record ui page in the ala-hub.
> Add materialSampleID to occurrence record endpoint

- README.md
- build.gradle
- src/main/java/au/org/ala/biocache/dao/SearchDAOImpl.java
- src/main/java/au/org/ala/biocache/dto/SearchRequestDTO.java
- src/main/java/au/org/ala/biocache/dto/SpatialSearchRequestParams.java
- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/test/java/au/org/ala/biocache/util/QueryFormatUtilsSpec.groovy
> #935 solr tagging and excluding filters

- src/main/java/au/org/ala/biocache/service/EmailService.java
This PR adds the possibility to use TLS and mail server authentication with the EmailService (used for notifications about downloaded records).
Using these options may look like this in the config file:
```
mail.smtp.host=mail.example.com
mail.smtp.port=587
mail.smtp.starttls.enable=true
mail.smtp.username=noreply@example.com
mail.smtp.password=abc123
```
> Add settings for TLS and mail server authentication to EmailService

- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/test/java/au/org/ala/biocache/util/QueryFormatUtilsSpec.groovy
> #940 Fix for qid query error

- src/main/java/au/org/ala/biocache/dao/SolrIndexDAOImpl.java
> #930 Filter unwanted fields from index/fields

- src/main/java/au/org/ala/biocache/util/QueryFormatUtils.java
- src/test/java/au/org/ala/biocache/dao/FilterQueryParserTest.java
- src/test/java/au/org/ala/biocache/dao/QueryFormatTest.java
issue #945 
- fixed a logic mistake, and
- replaced some regex, because apparently we support implied OR statements. QueryFormatUtils should be a parser based, not what it is currently.
> #945 fix queries with values containing colons

- src/main/java/au/org/ala/biocache/dto/UserAssertions.java
- src/main/java/au/org/ala/biocache/service/AssertionService.java
- src/main/java/au/org/ala/biocache/web/AssertionController.java
> #949 add param updateId to assertions add service
